package no.uio.ifi.in2000.warsamea.havvarsel.ui.symbol

import no.uio.ifi.in2000.warsamea.havvarsel.R

enum class WeatherSymbol(val symbolCode: String, val resourceId: Int) {
    DEFAULT("default", R.drawable.temp_icon),
    ClearskyDay("clearsky_day", R.drawable.clearsky_day),
    ClearskyNight("clearsky_night", R.drawable.clearsky_night),
    ClearskyPolar("clearsky_polartwilight", R.drawable.clearsky_polartwilight),
    Cloudy("cloudy", R.drawable.cloudy),
    FairDay("fair_day", R.drawable.fair_day),
    FairNight("fair_night", R.drawable.fair_night),
    FairPolar("fair_polartwilight", R.drawable.fair_polartwilight),
    Fog("fog", R.drawable.fog),
    Heavyrain("heavyrain", R.drawable.heavyrain),
    HeavyrainAndThunder("heavyrainandthunder", R.drawable.heavyrainandthunder),
    HeavyrainShowersDay("heavyrainshowers_day", R.drawable.heavyrainshowers_day),
    HeavyrainShowersNight("heavyrainshowers_night", R.drawable.heavyrainshowers_night),
    HeavyrainShowersPolar("heavyrainshowers_polartwilight", R.drawable.heavyrainshowers_polartwilight),
    HeavyrainShowersAndThunderDay("heavyrainshowersandthunder_day", R.drawable.heavyrainshowersandthunder_day),
    HeavyrainShowersAndThunderNight("heavyrainshowersandthunder_night", R.drawable.heavyrainshowersandthunder_night),
    HeavyrainShowersAndThunderPolar("heavyrainshowersandthunder_polartwilight", R.drawable.heavyrainshowersandthunder_polartwilight),
    Heavysleet("heavysleet", R.drawable.sleet),
    HeavysleetAndThunder("heavysleetandthunder", R.drawable.heavysleetandthunder),
    HeavysleetShowersDay("heavysleetshowers_day", R.drawable.heavysleetshowers_day),
    HeavysleetShowersNight("heavysleetshowers_night", R.drawable.heavysleetshowers_night),
    HeavysleetShowersPolar("heavysleetshowers_polartwilight", R.drawable.heavysleetshowers_polartwilight),
    HeavysleetShowersAndThunderDay("heavyslettshowersandthunder_day", R.drawable.heavysleetshowersandthunder_day),
    HeavysleetShowersAndThunderNight("heavyslettshowersandthunder_night", R.drawable.heavysleetshowersandthunder_night),
    HeavysleetShowersAndThunderPolar("heavyslettshowersandthunder_polartwilight", R.drawable.heavysleetshowersandthunder_polartwilight),
    Heavysnow("heavysnow", R.drawable.heavysnow),
    HeavysnowAndThunder("heavysnowandthunder", R.drawable.heavysnowandthunder),
    HeavysnowShowersDay("heavysnowshowers_day", R.drawable.heavysnowshowers_day),
    HeavysnowShowersNight("heavysnowshowers_night", R.drawable.heavysnowshowers_night),
    HeavysnowShowersPolar("heavysnowshowers_polartwilight", R.drawable.heavysnowshowers_polartwilight),
    HeavysnowShowersAndThunderDay("heavysnowshowersandthunder_day", R.drawable.heavysnowshowersandthunder_day),
    HeavysnowShowersAndThunderNight("heavysnowshowersandthunder_night", R.drawable.heavysnowshowersandthunder_night),
    HeavysnowShowersAndThunderPolar("heavysnowshowersandthunder_polartwilight", R.drawable.heavysnowshowersandthunder_polartwilight),
    Lightrain("lightrain", R.drawable.lightrain),
    LightrainAndThunder("lightrainandthunder", R.drawable.lightrainandthunder),
    LightrainShowersDay("lightrainshowers_day", R.drawable.lightrainshowers_day),
    LightrainShowersNight("lightrainshowers_night", R.drawable.lightrainshowers_night),
    LightrainShowersPolar("lightrainshowers_polartwilight", R.drawable.lightrainshowers_polartwilight),
    LightrainShowersAndThunderDay("lightrainshowersandthunder_day", R.drawable.lightrainshowersandthunder_day),
    LightrainShowersAndThunderNight("lightrainshowersandthunder_night", R.drawable.lightrainshowersandthunder_night),
    LightrainShowersAndThunderPolar("lightrainshowersandthunder_polartwilight", R.drawable.lightrainshowersandthunder_polartwilight),
    Lightsleet("lightsleet", R.drawable.lightsleet),
    LightsleetAndThunder("lightsleetandthunder", R.drawable.lightsleetandthunder),
    LightsleetShowersDay("lightsleetshowers_day", R.drawable.lightsleetshowers_day),
    LightsleetShowersNight("lightsleetshowers_night", R.drawable.lightsleetshowers_night),
    LightsleetShowersPolar("lightsleetshowers_polartwilight", R.drawable.lightsleetshowers_polartwilight),
    Lightsnow("lightsnow", R.drawable.lightsnow),
    LightsnowAndThunder("lightsnowandthunder", R.drawable.lightsnowandthunder),
    LightsnowShowersDay("lightsnowshowers_day", R.drawable.lightsnowshowers_day),
    LightsnowShowersNight("lightsnowshowers_night", R.drawable.lightsnowshowers_night),
    LightsnowShowersPolar("lightsnowshowers_polartwilight", R.drawable.lightsnowshowers_polartwilight),
    LightssleetShowersAndThunderDay("lightssleetshowersandthunder_day", R.drawable.lightssleetshowersandthunder_day),
    LightssleetShowersAndThunderNight("lightssleetshowersandthunder_night", R.drawable.lightssleetshowersandthunder_night),
    LightssleetShowersAndThunderPolar("lightssleetshowersandthunde_polartwilightr", R.drawable.lightssleetshowersandthunder_polartwilight),
    LightssnowShowersAndThunderDay("lightssnowshowersandthunder_day", R.drawable.lightssnowshowersandthunder_day),
    LightssnowShowersAndThunderNight("lightssnowshowersandthunder_night", R.drawable.lightssnowshowersandthunder_night),
    LightssnowShowersAndThunderPolar("lightssnowshowersandthunder_polartwilight", R.drawable.lightssnowshowersandthunder_polartwilight),
    PartlycloudyDay("partlycloudy_day", R.drawable.partlycloudy_day),
    PartlycloudyNight("partlycloudy_night", R.drawable.partlycloudy_night),
    PartlycloudyPolar("partlycloudy_polartwilight", R.drawable.partlycloudy_polartwilight),
    Rain("rain", R.drawable.rain),
    RainAndThunder("rainandthunder", R.drawable.rainandthunder),
    RainShowersDay("rainshowers_day", R.drawable.rainshowers_day),
    RainShowersNight("rainshowers_night", R.drawable.rainshowers_night),
    RainShowersPolar("rainshowers_polartwilight", R.drawable.rainshowers_polartwilight),
    RainShowersAndThunderDay("rainshowersandthunder_day", R.drawable.rainshowersandthunder_day),
    RainShowersAndThunderNight("rainshowersandthunder_night", R.drawable.rainshowersandthunder_night),
    RainShowersAndThunderPolar("rainshowersandthunder_polartwilight", R.drawable.rainshowersandthunder_polartwilight),
    Sleet("sleet", R.drawable.sleet),
    SleetAndThunder("sleetandthunder", R.drawable.sleetandthunder),
    SleetShowersDay("sleetshowers_day", R.drawable.sleetshowers_day),
    SleetShowersNight("sleetshowers_night", R.drawable.sleetshowers_night),
    SleetShowersPolar("sleetshowers_polartwilight", R.drawable.sleetshowers_polartwilight),
    SleetShowersAndThunderDay("sleetshowersandthunder_day", R.drawable.sleetshowersandthunder_day),
    SleetShowersAndThunderNight("sleetshowersandthunder_night", R.drawable.sleetshowersandthunder_night),
    SleetShowersAndThunderPolar("sleetshowersandthunder_polartwilight", R.drawable.sleetshowersandthunder_polartwilight),
    Snow("snow", R.drawable.snow),
    SnowAndThunder("snowandthunder", R.drawable.snowandthunder),
    SnowShowersDay("snowshowers_day", R.drawable.snowshowers_day),
    SnowShowersNight("snowshowers_night", R.drawable.snowshowers_night),
    SnowShowersPolar("snowshowers_polartwilight", R.drawable.snowshowers_polartwilight),
    SnowShowersAndThunderDay("snowshowersandthunder_day", R.drawable.snowshowersandthunder_day),
    SnowShowersAndThunderNight("snowshowersandthunder_night", R.drawable.snowshowersandthunder_night),
    SnowShowersAndThunderPolar("snowshowersandthunder_polartwilight", R.drawable.snowshowersandthunder_polartwilight);

    companion object {
        fun fromSymbolCode(symbolCode: String?): WeatherSymbol {
            return entries.find { it.symbolCode.contains(symbolCode.toString(), ignoreCase = true) } ?: DEFAULT
        }
    }
}
