package no.uio.ifi.in2000.warsamea.havvarsel.ui.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

data class Dimens(
    val extraExtraSmall: Dp = 0.dp,
    val extraExtraSmallmorescreen: Dp = 0.dp,
    val extraSmall: Dp = 0.dp,
    val extraSmallmorescreen: Dp = 0.dp,
    val small1: Dp = 0.dp,
    val small2: Dp = 0.dp,
    val small3: Dp = 0.dp,
    val smallmorescreen1: Dp = 0.dp,
    val smallmorescreen2: Dp = 0.dp,
    val smallmorescreen3: Dp = 0.dp,
    val medium1: Dp = 0.dp,
    val medium2: Dp = 0.dp,
    val medium3: Dp = 0.dp,
    val mediummorescreen1: Dp = 0.dp,
    val mediummorescreen2: Dp = 0.dp,
    val mediummorescreen3: Dp = 0.dp,
    val large: Dp = 0.dp,
    val largemorescreen: Dp = 0.dp,
    val iconSize: Dp = 24.dp,
    val iconSizeHeader: Dp = 24.dp,
    val iconSizeMoreScreen: Dp = 28.dp,
    val iconSizealertsMoreScreen: Dp = 28.dp,
    val iconSizeMoreScreenheader: Dp = 18.dp,
    val imageHeight: Dp = 250.dp,
    val imageWidth: Dp = 100.dp,
    val boxheight: Dp = 100.dp,
    val boxwidth: Dp = 100.dp,
    val boxsize: Dp = 24.dp,
    val boxBoatScreen: Dp = 16.dp,
    val boatMove: Dp = 30.dp,
    val moreMove: Dp = 30.dp

)

val CompactDimens = Dimens(
    extraExtraSmall = 2.dp,
    extraExtraSmallmorescreen = 2.dp,
    extraSmall = 4.dp,
    small1 = 8.dp,
    small2 = 16.dp,
    small3 = 20.dp,
    smallmorescreen1 = 8.dp,
    smallmorescreen2 = 16.dp,
    smallmorescreen3 = 20.dp,
    medium1 = 30.dp,
    medium2 = 36.dp,
    medium3 = 40.dp,
    mediummorescreen1 = 30.dp,
    mediummorescreen2 = 36.dp,
    mediummorescreen3 = 40.dp,
    large = 45.dp,
    largemorescreen = 45.dp,
    iconSize = 20.dp,
    iconSizeHeader = 20.dp,
    iconSizeMoreScreen = 28.dp,
    iconSizealertsMoreScreen = 28.dp,
    iconSizeMoreScreenheader = 18.dp,
    imageHeight = 250.dp,
    boxBoatScreen = 16.dp,
    imageWidth = 100.dp,
    boxsize = 24.dp,
    boatMove = 30.dp,
    moreMove = 30.dp
)

val CompactSmallDimens = Dimens(
    extraExtraSmall = 2.dp,
    extraExtraSmallmorescreen = 2.dp,
    extraSmall = 4.dp,
    small1 = 6.dp,
    small2 = 16.dp,
    small3 = 10.dp,
    smallmorescreen1 = 6.dp,
    smallmorescreen2 = 14.dp,
    smallmorescreen3 = 20.dp,
    medium1 = 30.dp,
    medium2 = 30.dp,
    medium3 = 40.dp,
    mediummorescreen1 = 30.dp,
    mediummorescreen2 = 36.dp,
    mediummorescreen3 = 40.dp,
    large = 70.dp,
    largemorescreen = 45.dp,
    iconSize = 36.dp,
    iconSizeHeader = 20.dp,
    iconSizeMoreScreen = 19.dp,
    iconSizealertsMoreScreen = 28.dp,
    boxBoatScreen = 16.dp,
    iconSizeMoreScreenheader = 18.dp,
    imageHeight = 250.dp,
    imageWidth = 80.dp,
    boxsize = 24.dp,
    boatMove = 95.dp,
    moreMove = 120.dp
)


//Medium size screen like pixel etc.
val CompactMediumDimens = Dimens(
    extraExtraSmallmorescreen = 2.dp,
    extraExtraSmall = 2.dp,
    extraSmall = 4.dp,
    small1 = 8.dp,
    small2 = 16.dp,
    small3 = 20.dp,
    smallmorescreen1 = 8.dp,
    smallmorescreen2 = 10.dp,
    smallmorescreen3 = 20.dp,
    medium1 = 16.dp,
    medium2 = 36.dp,
    medium3 = 40.dp,
    mediummorescreen1 = 30.dp,
    mediummorescreen2 = 36.dp,
    mediummorescreen3 = 40.dp,
    large = 70.dp,
    largemorescreen = 45.dp,
    iconSize = 55.dp,
    iconSizeMoreScreen = 20.dp,
    iconSizealertsMoreScreen = 33.dp,
    iconSizeMoreScreenheader = 18.dp,
    iconSizeHeader = 20.dp,
    boxheight = 125.dp,
    boxwidth = 75.dp,
    boxBoatScreen = 16.dp,
    imageHeight = 250.dp,
    imageWidth = 100.dp,
    boxsize = 24.dp,
    boatMove = 100.dp,
    moreMove = 130.dp
)

//Tablets
val CompactLargeDimens = Dimens(
    extraExtraSmall = 2.dp,
    extraExtraSmallmorescreen = 2.dp,
    extraSmall = 2.dp,
    small1 = 6.dp,
    small2 = 5.dp,
    small3 = 8.dp,
    smallmorescreen1 = 8.dp,
    smallmorescreen2 = 16.dp,
    smallmorescreen3 = 20.dp,
    medium1 = 15.dp,
    medium2 = 26.dp,
    medium3 = 30.dp,
    mediummorescreen1 = 30.dp,
    mediummorescreen2 = 36.dp,
    mediummorescreen3 = 40.dp,
    large = 45.dp,
    largemorescreen = 45.dp,
    iconSize = 20.dp,
    boxBoatScreen = 16.dp,
    iconSizeMoreScreen = 28.dp,
    iconSizealertsMoreScreen = 28.dp,
    iconSizeMoreScreenheader = 18.dp,
    iconSizeHeader = 20.dp,
    imageHeight = 250.dp,
    imageWidth = 100.dp,
    boxsize = 24.dp,
    boatMove = 300.dp,
    moreMove = 300.dp

)